<a href="https://colab.research.google.com/github/micanoas/Micanoas/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
d = [1,2,3,4,5,6]
arr = np.array(d)
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
np.shape(arr)

(6,)

In [ ]:
np.size(arr)

6

In [ ]:
d2 = [[1,3,5,7], [3,55,6,90]]
arr1 = np.array(d2)
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [ ]:
np.shape(arr1)

(2, 4)

In [ ]:
arr1[1,2]

6

In [ ]:
arr1[0, :]

array([1, 3, 5, 7])

In [ ]:
arr1[1, 1:3]

array([55,  6])

In [ ]:
np.empty(6, dtype="int32")

array([         0,          0,          0, 1071644672,          0,
       1072693248], dtype=int32)

In [ ]:
np.empty([2,2], dtype="int32")

array([[ 1262746869, -2117160148],
       [  186531736,       32305]], dtype=int32)

In [ ]:
np.random.randint(0,57, size=(3,3))

array([[26, 31, 40],
       [28, 50, 20],
       [24, 21,  0]])

In [ ]:
np.random.rand(3,3)

array([[0.44290338, 0.12092238, 0.99933057],
       [0.33284389, 0.19234595, 0.19088315],
       [0.01394717, 0.44126807, 0.02807526]])

In [ ]:
arr1

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [ ]:
arr3 = arr1 * 2
arr3

array([[  2,   6,  10,  14],
       [  6, 110,  12, 180]])

In [ ]:
arr33 = arr1 / 2
arr33

array([[ 0.5,  1.5,  2.5,  3.5],
       [ 1.5, 27.5,  3. , 45. ]])

In [ ]:
subarr = np.subtract(arr3, arr1)
subarr

array([[ 1,  3,  5,  7],
       [ 3, 55,  6, 90]])

In [ ]:
arr1.mean()

21.25

In [ ]:
arr1.cumsum(axis=1)

array([[  1,   4,   9,  16],
       [  3,  58,  64, 154]])

In [ ]:
arr4 = np.arange(8)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr5 = arr4.reshape(4,2)
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
arr6 = arr5.reshape(2,4)
arr6

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr7 = arr6.T
arr7

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
arr8 = np.concatenate((arr5, arr7))
arr8

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [ ]:
np.split(arr7, 2)

[array([[0, 4],
        [1, 5]]),
 array([[2, 6],
        [3, 7]])]